env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
language: c
sudo: required
cache:
  directories:
    - ${DEPS_DIR}/doxygen/doxygen-1.8.11/bin
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1
      compiler: clang
  allow_failures:
    - os: osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - llvm-5.0
      - llvm-5.0-dev
      - lld-5.0
      - liblz4-dev
      - graphviz
      - python3
      - python3-pip

install:
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

    # Travis has an OLD doxygen build, so we fetch a recent one
    - export DOXY_BINPATH=${DEPS_DIR}/doxygen/doxygen-1.8.11/bin
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then mkdir -p ${DEPS_DIR}/doxygen; fi
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz; fi
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then tar xzf doxygen-1.8.11.linux.bin.tar.gz -C ${DEPS_DIR}/doxygen/; fi
    - export PATH=$PATH:$DOXY_BINPATH
before_script:
  # macos specific stuff
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install llvm qemu lz4; 
      export PATH=\"/usr/local/opt/llvm/bin:$PATH\";
	  ln -s /usr/local/opt/llvm/bin/clang++ /usr/local/opt/llvm/bin/clang++-5.0;
	  ln -s /usr/local/opt/llvm/bin/ld.lld /usr/local/opt/llvm/bin/ld.lld-5.0; fi"
  - git clone https://github.com/reswitched/unicorn.git
  - cd unicorn
  - UNICORN_ARCHS="aarch64" ./make.sh
  - sudo ./make.sh install
  - cd ..
  - git clone https://github.com/reswitched/Mephisto.git
  - cd Mephisto
  - sudo pip2 install -r  requirements.txt
  - make
  - cd ..
  - sudo pip3 install -r  requirements.txt
script:  make LLVM_POSTFIX=-5.0 LD=ld.lld-5.0 && make -C projects/ace_loader LLVM_POSTFIX=-5.0 LD=ld.lld-5.0 && make run_tests MEPHISTO=./Mephisto/ctu

after_success:
  #Once the build has passed, build the docs
  - doxygen Doxyfile

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  target-branch: gh-pages
  on:
    branch: master
