env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
language: c
sudo: required
cache:
  directories:
    - ${DEPS_DIR}/doxygen/doxygen-1.8.11/bin
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1
      compiler: clang
  allow_failures:
    - os: osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - llvm-5.0
      - llvm-5.0-dev
      - lld-5.0
      - liblz4-dev
      - squashfs-tools
      - graphviz
      - python3
      - python3-pip
install:
    # Set postfix variable
    - export LLVM_POSTFIX=-5.0

    # Download and install recent cmake (linux only)
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
      
    # Setup Mac packages (no brew plugin) and remove -5.0 postfix
    - |
      if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        export LLVM_POSTFIX="";
        brew install llvm qemu lz4 python3 squashfs
        export PATH="/usr/local/opt/llvm/bin:$PATH";
      fi

    # Travis has an OLD doxygen build, so we fetch a recent one
    - export DOXY_BINPATH=${DEPS_DIR}/doxygen/doxygen-1.8.11/bin
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then mkdir -p ${DEPS_DIR}/doxygen; fi
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz; fi
    - if [ ! -e "$DOXY_BINPATH/doxygen" ]; then tar xzf doxygen-1.8.11.linux.bin.tar.gz -C ${DEPS_DIR}/doxygen/; fi
    - export PATH=$PATH:$DOXY_BINPATH

before_script:
  - git clone https://github.com/reswitched/unicorn.git
  - cd unicorn
  - UNICORN_ARCHS="aarch64" ./make.sh
  - sudo ./make.sh install
  - cd ..
  - git clone https://github.com/reswitched/Mephisto.git
  - cd Mephisto
  - sudo pip2 install -r  requirements.txt
  - make CC=clang++$LLVM_POSTFIX LD=ld.lld$LLVM_POSTFIX
  - cd ..
  - sudo pip3 install -r  requirements.txt
  
script:  make LD=ld.lld$LLVM_POSTFIX && LD=ld.lld$LLVM_POSTFIX make -C projects/ace_loader && make run_tests MEPHISTO=./Mephisto/ctu

after_success:
  # Once the build has passed, build the docs
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then doxygen Doxyfile; fi
  # Package tests for deployment
  - cd build/test/
  - tar czvf tests_nro.tar.gz test_*.nro
  - tar czvf tests_nso.tar.gz test_*.nso
  - cd ../../
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    target-branch: gh-pages
    on:
      branch: development
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "projects/ace_loader/ace.nro"
      - "build/test/tests_nro.tar.gz"
      - "build/test/tests_nso.tar.gz"
    skip-cleanup: true
    draft: true
    tag_name: $TRAVIS_TAG
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
